<h2 id="tituloEmail">Remitente y Destinatario de los Emails Autom&aacute;ticos</h2>
<h3>Remitente y Destinatario de los Emails Autom&aacute;ticos | <a href="/configuracion">Regresar a Configuraci&oacute;n</a></h3>

<div class="info">Aqu&iacute; usted podr&aacute; definir desde cual cuenta de correo saldr&aacute;n los emails autom&aacute;ticos, as&iacute; como qui&eacute;n recibir&aacute; los reportes que genera autom&aacute;ticamente el sistema</div>
<?=$this->form->render()?>
