        <div id="content1">
          <div class="indent">
            <div class="wrapper">
              <div class="col-3" style="width:900px">
                <div class="title1">
                	<div class="ico"><img src="/images/3page-title2.gif" alt="" /></div>
                	<div class="text_big_title" style="padding-top:15px">Nuestros Aliados</div>
                </div>
                <p class="p1_justify">
     	          En la pr&aacute;ctica, todo emprendimiento de cierta magnitud cuenta con la ayuda de amigos y aliados, 
     	          aquellas personas u organizaciones que con su aporte hacen que un proyecto sea posible. En esta
     	          secci&oacute;n reconocemos la labor de nuestros aliados. </p>
				<p class="p1_justify">
     	          	<a href="/contacto">&iquest;Quieres aparecer en esta p&aacute;gina como nuestro cliente?</a>
     	        </p>
				<p class="p1_justify">
     	          	<a href="/contacto">&iquest;Ofreces alg&uacute;n producto o servicio que nos podr&iacute;a 
     	          	ser de utilidad?</a>
     	        </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>    
    <div id="main2">
      <!-- content2 -->
      <div id="content2">
        <div class="wrapper">
          <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/5page-title3.gif" alt="Nuestros Clientes" /></div>
            	<div class="text_big_title" style="line-height:1em;margin-bottom:50px">Nuestros Clientes</div>
            </div>              
            <p class="p1_justify" style="text-indent:10px">El <b>Sistema de Gesti&oacute;n Legal</b> no existir&iacute;a 
            sin el inter&eacute;s y aporte de nuestros clientes. Aqu&iacute; le mostramos una lista de algunos de 
            nuestros clientes.</p>
            <div class="wrapper"><a href="/contacto" class="link1">
            	<em><b>&iquest;Te gustar&iacute;a estar aqu&iacute;?</b></em></a>
            </div>
          </div>
          <div class="col-2">
            <div class="title1"><img src="/images/5page-title5.gif" alt="" /></div>
            <ul class="list3">
              <li>
              	<a href="http://www.tamayo-tamayo.com" target="_blank">
              		<img src="/images/aliados/logo-tamayo.gif" alt="" />Ver p&aacute;gina
              	</a>
              </li>
              <li style="width:100px">
              	Escritorio Jur&iacute;dico Areyan Salazar & Asociados
              </li>
              <!--<li class="last"><a href="#"><img src="/images/extra-logo5.gif" alt="" />Read more</a></li>-->
            </ul>
          </div>
        </div>
      </div>
      <div id="content2">
        <div class="wrapper">
          <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/5page-title1.gif" alt="Nuestros Proveedores" /></div>
            	<div class="text_big_title" style="line-height:1.15em;margin-bottom:30px">Proveedores y Otros Aliados</div>
            </div>            
            <p class="p2">Algunos de nuestros proveedores y aliados m&aacute;s importantes.</p>
            <div class="wrapper"><a href="/contacto" class="link1"><em><b>&iquest;Quieres ofrecernos alg&uacute;n servicio?</b></em></a></div>
          </div>
          <div class="col-2">
            <div class="title1"><img src="/images/5page-title5.gif" alt="" /></div>
            <ul class="list3">
              <li><a href="http://www.inmotionhosting.com" target="_blank"><img src="/images/aliados/logo-inmotionhosting.gif" alt="" />Hosting confiable 24/7/365</a></li>
              <!--<li class="last"><a href="#"><img src="/images/extra-logo5.gif" alt="" />Read more</a></li>-->
            </ul>
          </div>
        </div>
      </div>      