<link href="http://admin.sistemadegestionlegal.com/css/forms.css" media="screen" rel="stylesheet" type="text/css" >
<style>
	form{width:600px}
	fieldset{border:0px;height: 350px}
	#Enviar{margin-left: 50%;float: left} 
</style>
    <div id="main2">
      <!-- content2 -->
      <div id="content2">
        <div class="wrapper">
          <div class="col-1">
                <div class="title1">
                	<div class="ico"><img src="/images/6page-title3.gif" alt="" /></div>
                	<div class="text_big_title" style="padding-top:15px">Cont&aacute;ctenos</div>
                </div>
            <?=$this->form->render()?>
				<div class="title1">
                	<div class="ico"><img src="/images/Mail-icon.png" alt="Email" /></div>
                	<div class="text_big_title" style="padding-top:15px;padding-left:65px"> Correo Electr&oacute;nico</div>
                	<div class="p1">Si lo desea nos puede contactar a trav&eacute;s de la siguiente direcci&oacute;n
                	de correo electr&oacute;nico:</div>
                	<div class="p1" style="text-align:center">
                	<img src="/images/emailcontacto.png">
                	</div>
                </div>
			</div>
          <div class="col-2">
                <div class="title1">
                	<div class="ico"><img src="/images/6page-title5.gif" alt="" /></div>
                	<div class="text_big_title" style="padding-top:15px">Informaci&oacute;n</div>
                </div>
            <p class="p1">A trav&eacute;s del formulario a su izquierda usted podr&aacute; comunicarse con 
            	<a href="/nosotros">nosotros</a> y solicitar una cotizaci&oacute;n del <b>Sistema de Gesti&oacute;n
            	Legal</b>, o si lo desea, m&aacute;s informaci&oacute;n sobre nuestros productos y servicios.</p>
				<div class="text_title" style="text-align:left">&iquest;Por qu&eacute; requerimos su Email?</div>
            <p class="p1">Es necesario que usted nos de su email para nosotros poder contactarle.</p>
				<div class="text_title" style="text-align:left">&iquest;Vamos a publicar su Email?</div>
            <p class="p1">Absolutamente NO. Tampoco lo venderemos o cederemos a terceros. Su email y dem&aacute;s
            datos son recibidos en forma estrictamente confidencial y como tal se mantienen.</p>
				<div class="text_title">&iquest;Recibir&eacute; alg&uacute;n spam de ustedes?</div>
            <p class="p1">El spam o correo basura es una pr&aacute;ctica poco profesional que nuestra empresa
            no practica. Por lo tanto, usted no recibir&aacute; ning&uacute;n tipo de comunicaci&oacute;n indeseada
            de nuestra parte. Si nosotros le contactamos es con su previo consentimiento.</p>
          </div>

        </div>
      </div>
