<link href="http://admin.sistemadegestionlegal.com/css/forms.css" media="screen" rel="stylesheet" type="text/css" >
<style>
	form{width:600px}
	fieldset{border:0px;height: 120px}
	#Entrar{margin-left: 40%} 
</style>


    <div style="text-align:center;margin-top:50px;width:700px;padding-left:20%">
    <div style="display:inline">
		<iframe width="425" height="349" src="http://www.youtube.com/embed/MwPrGHym1t4?hl=en&fs=1" frameborder="0" allowfullscreen></iframe>
	</div>
	<div style="float:right;margin-left:20px;width:250px;text-align:justify;line-height:25px">
	            <div class="title1">
            	<div class="ico" style="padding-right:10px"><img src="/images/Video-icon.png" alt="" /></div>
            	<div class="text" style="text-align:left;margin-left:5px;padding-top:10px">Video del demo SGL</div>
            </div>
		<div style="margin-top:30px;text-indent:15px">
		En este video de 1 minuto te demostramos de manera sencilla la manera como funciona el Sistema de Gesti&oacute;n Legal 
		y lo que ofrecemos para tu escritorio jur&iacute;dico. Haz clic en el video a tu izquierda.
		</div>
	</div>
    </div>

	<div id="content1" style="margin-top:65px">
	                <div class="title1">
                	<div class="ico"><img src="/images/3page-title2.gif" alt="" /></div>
                	<div class="text_big_title">Demo del <b>Sistema de Gesti&oacute;n Legal</b></div>
                </div>
				<div class="text_title">&iquest;C&oacute;mo acceder al SGL?</div>
				<p class="p1_justify">Existen dos formas de acceder al demo del <b>Sistema de Gesti&oacute;n Legal</b></p>
				<p class="p1_justify"><b>Nota:</b> el demo se abrir&aacute; en una nueva p&aacute;gina.</p>
	</div>
    <div id="main2">
      <!-- content2 -->
      <div id="content2">
        <div class="wrapper">
       
	          	<div class="col-1" style="width:500px">
                <div class="title1">
                	<div class="ico"><img src="/images/6page-title3.gif" alt="" /></div>
                	<div class="text_big_title" style="padding-top:15px">Utilizando el siguiente formulario</div>
                	<p class="p1_justify">Recuerde que el password es <b>123</b></p>
                </div>
            <?=$this->form->render()?>
			</div>
          <div class="col-2">
                <div class="title1">
                	<div class="ico"><img src="/images/6page-title2.gif" alt="" /></div>
                	<div class="text_big_title" style="padding-top:15px">URL del SGL</div>
                </div>
            <p class="p1">El <b>Sistema de Gesti&oacute;n Legal</b> vive en la url 
                	<a href="http://admin.sistemadegestionlegal.com/index/index/username/admin@demo.com" target="_blank">
                		<em style="font-size:larger">http://admin.sistemadegestionlegal.com</em>
                	</a>
			</p>
			<p class="p1">Para usar el demo debe ingresar los siguientes datos:</p>
                <ul style="margin-left:15%">
                	<li>E-mail: <b>admin@demo.com</b></li>
                	<li>Clave: <b>123</b></li>
                </ul>
            </p>           
          </div>
 <div class="col-3"  style="width:900px">
	    <div class="title1">
	    	<div class="ico"><img src="images/1page-title1.gif" alt="Detalles del Sistema de Gesti&oacute;n Legal" /></div>
	    	<div class="text_big_title" style="padding-top:15px;padding-left:67px">Detalles del Sistema de Gesti&oacute;n Legal</div>
	    </div>
		<p class="p1_justify">
				El <b>Sistema de Gesti&oacute;n Legal</b> es un servicio que se ofrece en la <b>nube</b>, es decir, internet. A trav&eacute;s de <a href="http://admin.sistemadegestionlegal.com" target="_blank">admin.sistemadegestionlegal.com</a> usted ingresar&aacute; un usuario y contrase&ntilde;a <b>privados</b>, conocidos &uacute;nicamente por usted, que le dar&aacute;n acceso a su <b>escritorio jur&iacute;dico virtual</b>.
        </p>
		<p class="p1_justify">
				En este espacio usted encontrar&aacute; una serie de herramientas organizadas por <b>m&oacute;dulos</b>. 
        </p>
		<p class="p1_justify">
				Los <b>m&oacute;dulos</b> principales son: <b>clientes</b>, <b>abogados</b> y <b>casos</b>.
        </p>
		<p class="p1_justify">
				En el <b>m&oacute;dulo de clientes</b> se puede administrar la informaci&oacute;n relacionada con sus <b>clientes</b>. Aqu&iacute; podr&aacute; subir los datos principales de los mismos, como su ficha biogr&aacute;fica, datos de contactos, etc, y darles acceso a su <b>p&aacute;gina web</b>.
        </p>
		<p class="p1_justify">
				En el <b>m&oacute;dulo de abogados</b> se puede administrar la informaci&oacute;n relacionada con los <b>abogados</b> que trabajan para su <b>escritorio jur&iacute;dico</b> u otros <b>abogados</b> de confianza. Por ejemplo, usted podr&aacute; almacenar la ficha biogr&aacute;fica del <b>abogado</b>, su <b>especialidad</b>, datos de contacto y s&iacute;ntesis curricular. Si usted se desempe&ntilde;a como <b>profesional independiente</b>, tambi&eacute;n puede almacenar sus datos en este m&oacute;dulo.
        </p>
		<p class="p1_justify">
				El <b>m&oacute;dulo de casos</b> act&uacute;a como puente entre los dos <b>m&oacute;dulos</b> anteriores. Un <b>caso</b> involucra a uno o m&aacute;s <b>clientes</b> con uno o m&aacute;s <b>abogados</b> de su <b>escritorio jur&iacute;dico</b>. En el <b>caso</b> usted puede almacenar nombre, <b>n&uacute;mero de expediente</b>, fecha de inicio y dem&aacute;s datos relevantes. 
        </p>
		<p class="p1_justify">
				Una vez creado un <b>caso</b> a el mismo se le puede a&ntilde;adir <b>historial</b>. En el <b>historial</b> se refleja el avance del caso desde su inicio hasta finalizaci&oacute;n. En cada etapa del mismo se puede subir un archivo .pdf con informaci&oacute;n relevante, por ejemplo, alguna <b>sentencia</b> o comunicaci&oacute;n emitida por <b>tribunales</b>. Una vez actualizada la <b>historia de un caso</b> se le enviar&aacute; un <b>email</b> a los <b>clientes</b> de dicho caso con un mensaje donde se les indica la actualizaci&oacute;n del mismo y se les invita a ingresar a la <b>p&aacute;gina web del escritorio jur&iacute;dico</b> para ver m&aacute;s detalles. De esta forma se mantiene al <b>cliente</b> mejor informado sin costos extras o necesidad de intermediarios.
        </p>
		<p class="p1_justify">
				Estas son algunas de las funcionalidades del <b>Sistema de Gesti&oacute;n Legal</b>. Le invitamos a ingresar al <a href="http://admin.sistemadegestionlegal.com/index/index/username/admin@demo.com" target="_blank">demo</a> (password: 123) y probar por usted mismo nuestra <b>plataforma</b>. Recuerde que al encontrarse en la <b>nube</b>, usted podr&aacute; disfrutar de <b>actualizaciones</b> futuras del software sin pagos extras u ocultos. Forme parte de nuestra <b>plataforma</b> hoy mismo y lleve su <b>escritorio jur&iacute;dico a la web</b>.
        </p>
     </div>          
		</div>
	</div>
     