
<style>ol li b{display: block;margin:5px}ol li{margin: 15px;text-indent: 5px;text-align: justify}</style>
<ol style="margin-top:50px;line-height:1.5em">
	<li>
		<b>&iquest;Qu&eacute; es <a href="/">SGL</a>? &iquest;Es un "programa"? &iquest;Un "software"?</b>
		<a href="/">SGL</a> o <a href="/">Sistema de Gesti&oacute;n Legal</a> es un servicio distribuido a trav&eacute;s de la Nube (Internet), dirigido a Escritorios Jur&iacute;dicos y Profesionales de las leyes. En pocas palabras el servicio automatiza las operaciones del d&iacute;a a d&iacute;a de estos profesionales. Al encontrarse en la Nube, <a href="/">SGL</a> funcionar&aacute; las <a href="/sistema">24 horas del d&iacute;a desde cualquier lugar del mundo</a> donde exista una conexi&oacute;n a Internet y se apalanca en otros servicios tales como el correo electr&oacute;nico para un &oacute;ptimo funcionamiento.
	</li>
	<li>
		<b>&iquest;Con <a href="/">SGL</a> puedo "olvidarme" de los papeles y ver todo lo que uso en mi d&iacute;a a d&iacute;a en la web?</b>
		Depende. En la actualidad las leyes de muchos pa&iacute;ses le obligan al profesional de las leyes mantener registros en f&iacute;sico de todos los documentos relacionados con su actividad diaria. Si es as&iacute;, usted no podr&aacute; olvidarse de los papeles f&iacute;sicos pero s&iacute; podr&aacute; subir una copia digital de dichos documentos en el <a href="/">Sistema de Gesti&oacute;n Legal</a>. Una vez los documentos est&eacute;n en la Nube, usted podr&aacute; organizarlos y buscarlos mucho m&aacute;s f&aacute;cil y r&aacute;pidamente que en su contraparte f&iacute;sica. Las ventajas de subir los documentos son muchas y le invitamos a probar el <a href="/demo">demo</a> de la aplicaci&oacute;n para obtener m&aacute;s informaci&oacute;n.
	</li>
	<li>
		<b>&iquest;Cu&aacute;nto espacio de almacenamiento da <a href="/">SGL</a>?</b>
		Suficiente para almacenar miles de registros (clientes, abogados, casos, leyes, etc). Si su escritorio necesita m&aacute;s de eso, siempre se puede expandir la capacidad a un costo muy bajo. <a href="/">SGL</a> se hospeda en servidores de primera l&iacute;nea a nivel mundial y emplea econom&iacute;as de escala para permitirle almacenar todo lo que necesite.
	</li>
	<li>
		<b>&iquest;Si mi escritorio juridico adquiere <a href="/">SGL</a>, cuantos usuarios y contrase&ntilde;as me da? &iquest;Uno por abogado socio?</b>
		Una vez usted forme parte de la plataforma de servicios de <a href="/">SGL</a>, se le otorgar&aacute; un usuario y contrase&ntilde;a principal con la cual podr&aacute; ingresar al sistema. Dentro del sistema usted podr&aacute; definir tantos usuarios como desee. Los usuarios son las personas que tienen acceso al sistema mientras que los abogados se registran en un m&oacute;dulo diferente, y son a qui&eacute;nes se les asignan los casos. En la actualidad, usted podr&aacute; agregar tantos abogados y usuarios como desee sin limitaci&oacute;n alguna. En el futuro se podr&iacute;an colocar restricciones las cuales se le informar&iacute;a al p&uacute;blico oportunamente. 
	</li>
	<li>
		<b>&iquest;C&oacute;mo s&eacute; que mis clientes tendr&aacute;n acceso restringido al sistema y no ver&aacute;n mis documentos privados?</b>
		El <a href="/">Sistema de Gesti&oacute;n Legal</a> puede ser conectado con la p&aacute;gina web de su bufete y s&oacute;lo en ese caso usted puede decidir otorgarle acceso a sus clientes a trav&eacute;s de dicha p&aacute;gina web. Los clientes acceden por un sitio web distinto del que usted ingresa al <a href="/">SGL</a> y por lo tanto s&oacute;lo tendr&aacute;n acceso a los casos de los cuales formen parte. Usted siempre tendr&aacute; la potestad, a trav&eacute;s del <a href="/">SGL</a>, de revocarle el acceso a un cliente. Sin embargo, una de las ventajas del sistema es mantener a sus clientes siempre informados de lo que ocurre con sus casos a trav&eacute;s de la web.
	</li>
	<li>
		<b>&iquest;Puedo usar <a href="/">SGL</a> en mi blackberry? &iquest;Iphone? &iquest;Y en android? &iquest;Tablet?</b>
		S&iacute;, el <a href="/">SGL</a> es accesible a trav&eacute;s de cualquier dispositivo que tenga un browser tal como Firefox, Safari, Internet Explorer, etc.
	</li>
	<li>
		<b>&iquest;Tengo acceso a todos los servicios de <a href="/">SGL</a> si solo adquiero el sistema por que ya tengo mi pagina web?</b>
		S&iacute;, pero para un &oacute;ptimo uso del sistema se recomienda conectar la p&aacute;gina web de su Escritorio con el <a href="/">SGL</a>.
	</li>
	<li>
		<b>&iquest;Qu&eacute; debo hacer para contratar los servicios del <a href="/">SGL</a>?</b>
		Solo debe contact&aacute;rnos haciendo clic <a href="/contacto">aqu&iacute;</a>
	</li>
</ol>