        <div id="content1">
          <div class="indent">
            <div class="wrapper">
              <div class="col-3" style="width:900px">
                <div class="title1">
                	<div class="ico"><img src="/images/3page-title4.gif" alt="" /></div>
                	<div class="text_big_title" style="padding-top:15px">&iexcl;Gracias por contactarnos!</div>
                </div>
                <p class="p1_justify" style="font-size:larger">
     	           Hemos recibido su mensaje correctamente y pronto estaremos en contacto con usted. 
     	           Queremos tomar esta oportunidad para agradecerle su inter&eacute;s en nuestra empresa
     	           y desearle el mayor de los &eacute;xitos para usted y su <b>Escritorio Jur&iacute;dico</b>.</p>
     	        <p class="p1">Le invitamos a seguir explorando nuestra p&aacute;gina web:
     	        	<ul class="list1">
     	        		<li><a href="/">Inicio</a></li>
     	        		<li><a href="/nosotros">Nosotros</a></li>
     	        		<li><a href="/sistema">El Sistema</a></li>
     	        		<li><a href="/demo">Demo</a></li>
     	        		<li><a href="/aliados">Aliados</a></li>
     	        		<li><a href="/contacto">Contacto</a></li>
     	        	</ul>
     	        </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<div id="main2">
      <!-- content2 -->
      <div id="content2">
        <div class="wrapper">
          <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/1page-title1.gif" alt="El equipo de desarrollo del SGL" /></div>
            	<div class="text_big_title"n style="line-height:1em">El equipo de desarrollo del SGL</div>
            </div>
			<p class="p1" style="line-height:1.25em">Detr&aacute;s del escenario existe un equipo de profesionales que mantienen el <b>Sistema de Gesti&oacute;n Legal</b> en permanente desarrollo y actualizaci&oacute;n, con el fin
            de que usted disfrute de las &uacute;ltimas tecnolog&iacute;as en Internet. Le invitamos a conocer un poco m&aacute;s sobre nuestra empresa.</p>
            <div class="wrapper"><a href="/nosotros" class="link1"><em><b>Ver m&aacute;s sobre la empresa...</b></em></a></div>
          </div>
          <div class="col-2">
            <div class="title1">
            	<div class="ico"><img src="/images/3page-title5.gif" alt="Aliados de nuestra empresa" /></div>
            	<div class="text_big_title"n style="line-height:1em">Aliados de nuestra empresa</div>
            </div>
            
            <p class="p1">Conozca a algunos de nuestros aliados</p>
            <div class="wrapper">
              <div class="col-1">
                <ul class="list1">
                  <li><a href="/aliados">Clientes:</a></li>
                  <li><a href="http://www.tamayo-tamayo.com" target="_blank">Escritorio Jur&iacute;dico Tamayo-Tamayo</a></li>
                  <li>Escritorio Jur&iacute;dico Areyan Salazar & Asociados</li>
                </ul>
              </div>
              <div class="col-2">
                <ul class="list1">
                  <li><a href="/aliados">Proveedores:</a></li>
                  <li><a href="http://www.inmotionhosting.com" target="_blank">Inmotionhosting.com</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>    