		<div id="content1" style="margin-top:35px">
          <div class="wrapper">

            <div class="col-2">
              <div class="box1">
                <div class="border-top">
                  <div class="border-right">
                    <div class="border-left">
                      <div class="left-top-corner">
                        <div class="right-top-corner">
                          <div class="inner">
                            <div class="aligncenter"><img src="/images/icon-2.gif" alt="" /></div>
                            <div class="title"><img src="/images/box1-title.gif" alt="El Sistema" /></div>
                            <ul class="list">
                              <li><a href="/sistema">Sistema de Gesti&oacute;n Legal</a></li>
                              <li><a href="/sistema">Ahorre tiempo y dinero</a></li>
                              <li><a href="/sistema">Plataforma Totalmente Web</a></li>
                              <li><a href="/sistema">F&aacute;cil de Utilizar</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="border-bot">
                  <div class="left-bot-corner">
                    <div class="right-bot-corner">
                      <div class="link"><a href="/sistema">Ver m&aacute;s...</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-3">
              <div class="box2">
                <div class="border-top">
                  <div class="border-right">
                    <div class="border-left">
                      <div class="left-top-corner">
                        <div class="right-top-corner">
                          <div class="inner">
                            <div class="aligncenter"><img src="/images/icon-3.gif" alt="" /></div>
                            <div class="title"><img src="/images/box2-title.gif" alt="Demo" /></div>
                            <ul class="list">
                              <li><a href="/demo">Demo del sistema</a></li>
                              <li><a href="/demo">100% funcional y operativo</a></li>
                              <li><a href="/demo">Pru&eacute;belo usted mismo</a></li>
                              <li><a href="/demo">&iquest;Ya vio el demo?</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="border-bot">
                  <div class="left-bot-corner">
                    <div class="right-bot-corner">
                      <div class="link"><a href="/demo">Ver m&aacute;s...</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-1">
              <div class="box">
                <div class="border-top">
                  <div class="border-right">
                    <div class="border-left">
                      <div class="left-top-corner">
                        <div class="right-top-corner">
                          <div class="inner">
                            <div class="aligncenter"><img src="/images/icon-1.gif" alt="" /></div>
                            <div class="title"><img src="/images/box-title.gif" alt="Nosotros" /></div>
                            <ul class="list">
                              <li><a href="/nosotros">&iquest;Qui&eacute;nes somos?</a></li>
                              <li><a href="/nosotros">&iquest;Qu&eacute; ofrecemos?</a></li>
                              <li><a href="/nosotros">&iquest;Por qu&eacute; nosotros?</a></li>
                              <li><a href="/nosotros">Nuestra Experiencia</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="border-bot">
                  <div class="left-bot-corner">
                    <div class="right-bot-corner">
                      <div class="link"><a href="/nosotros">Ver m&aacute;s...</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>            
            <div class="col-4">
              <div class="box3">
                <div class="border-top">
                  <div class="border-right">
                    <div class="border-left">
                      <div class="left-top-corner">
                        <div class="right-top-corner">
                          <div class="inner">
                            <div class="aligncenter"><img src="/images/icon-4.gif" alt="" /></div>
                            <div class="title"><img src="/images/box3-title.gif" alt="Contacto" /></div>
                            <ul class="list">
                              <li><a href="/contacto">Adquirir el SGL</a></li>
                              <li><a href="/contacto">Cont&aacute;ctanos</a></li>
                              <li><a href="/contacto">Danos tu opini&oacute;n</a></li>
                              <li><a href="/contacto">Ofertas</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>               
                <div class="border-bot">
                  <div class="left-bot-corner">
                    <div class="right-bot-corner">
                      <div class="link"><a href="/contacto">Ver m&aacute;s...</a></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    <div style="text-align:center;margin-top:50px;width:700px;padding-left:20%">
    <div style="display:inline">
		<iframe width="425" height="349" src="http://www.youtube.com/embed/SfRr3OUt6is?hl=en&fs=1" frameborder="0" allowfullscreen></iframe>
	</div>
	<div style="float:right;margin-left:20px;width:250px;text-align:justify;line-height:25px">
	            <div class="title1">
            	<div class="ico" style="padding-right:10px"><img src="/images/Video-icon.png" alt="" /></div>
            	<div class="text" style="text-align:left;margin-left:5px;padding-top:10px">Video SGL</div>
            </div>
		<div style="margin-top:30px;text-indent:15px">
		Conoce en s&oacute;lo 1 minuto lo que ofrecemos para tu escritorio jur&iacute;dico. Haz clic en el video a tu izquierda.
		</div>
	</div>
    </div>
    <div id="main2">
      <!-- content2 -->
      <div id="content2">
        <div class="wrapper">
          <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/1page-title1.gif" alt="" /></div>
            	<div class="text">Herramientas valiosas para su Escritorio Jur&iacute;dico</div>
            </div>
			<p class="p1">&iquest;Conoce usted los beneficios de nuestro <b>Sistema de Gesti&oacute;n Legal</b>?</p>
		  	<p class="p1">Haga un uso m&aacute;s eficiente de los recursos de su escritorio jur&iacute;dico. 
		  	Ahorre tiempo y dinero. Con nuestro <b>Sistema de Gesti&oacute;n Legal</b>, ahora usted podr&aacute; llevar 
		  	en <b>Internet</b> una base de datos de sus abogados, casos y clientes, concentrando en un s&oacute;lo lugar
		  	toda la informaci&oacute;n que usted necesita para una buena gesti&oacute;n de su <b>bufete</b>.
		  	</p>
            <div class="wrapper"><a href="/sistema" class="link1"><em><b>Ver m&aacute;s...</b></em></a></div>
          </div>
          <div class="col-2">
            <div class="title1">
            	<div class="ico"><img src="/images/1page-title2.gif" alt="" /></div>
            	<div class="text">Una p&aacute;gina Web ya no es suficiente</div>
            </div>	
            <p class="p1">&iquest;Para qu&eacute; tener una p&aacute;gina web si usted puede tener un 
            <b>Sistema de Gesti&oacute;n Legal</b>?</p>
            <p class="p1">La mejor manera de conocer una Plataforma Web no es hablando mucho de ella sino 
            			interactu&aacute;ndo con ella.</p>
            <p class="p1">Es por eso que para conocer mejor nuestro <b>Sistema de Gesti&oacute;n Legal</b>, le invitamos a 
            	probar el <a href="/demo">DEMO</a>.</p>
            <div class="wrapper"><a href="/demo" class="link1"><em><b>Probar Demo</b></em></a></div>
          </div>
          <div class="col-3">
            <div class="title1">
            	<div class="ico"><img src="/images/1page-title3.gif" alt="" /></div>
            	<div class="text">A&ntilde;ada valor para sus clientes</div>
            </div>
            <ul class="list1">
	            <li>&iquest;Interesado en adquirir el <b>Sistema de Gesti&oacute;n Legal?</b></li>
            </ul>
            <p class="p1">Solicite hoy mismo su <b>Sistema de Gesti&oacute;n Legal</b> y disfrute de los beneficios de contar 
            			con una plataforma en la Web que le ayude a organizar, gestionar y administrar su Escritorio 
            			Jur&iacute;dico.</p>
            <ul class="list1">
                <li><a href="/contacto"><b>S&iacute;, estoy interesado</b></a></li>
            </ul>
            <div class="wrapper"><a href="/contacto" class="link1"><em><b>Cont&aacute;ctanos</b></em></a></div>
          </div>
          
          
      <div class="col-3" style="margin-top:50px;width:900px">
	    <div class="title1">
	    	<div class="ico"><img src="/images/2page-title5.gif" alt="El Sistema de Gesti&oacute;n Legal" /></div>
	    	<div class="text_big_title" style="padding-top:15px">El Sistema de Gesti&oacute;n Legal</div>
	    </div>
        <p class="p1_justify">
			El <b>Sistema de Gesti&oacute;n Legal</b> va dirigido a <b>escritorios jur&iacute;dicos</b>, <b>abogados</b> y cualquier otra organizaci&oacute;n que desempeñe labores en el &aacute;rea <b>jur&iacute;dica</b>, que desee <b>automatizar</b> y </b><b>organizar</b> toda la informaci&oacute;n relacionada con el d&iacute;a a d&iacute;a de su actividad profesional.
		</p>
		<p class="p1_justify">
			El <b>Sistema de Gesti&oacute;n Legal</b> funciona bajo un novedoso esquema que rompe la manera tradicional de distribuir <b>software</b>, ya que se provee a trav&eacute;s del internet, por lo cual se evitar&aacute; la tediosa instalaci&oacute;n de un CD, y simplemente debe tener acceso a la red para disfrutar de sus servicios.
		</p>
		<p class="p1_justify">
			De esta manera, adem&aacute;s de simplificarle la instalaci&oacute;n, la <b>plataforma</b> le dar&aacute; constantes actualizaciones y ventajas a lo largo del tiempo, por lo que no est&aacute; adquiriendo un producto que se vuelve obsoleto con los a&ntilde;os, sino que est&aacute; participando en una <b>plataforma</b> de actualizaci&oacute;n constante.
		</p>
		<p class="p1_justify">
			Entre las ventajas del sistema de gesti&oacute;n legal est&aacute; el <b>acceso las 24 horas del d&iacute;a, los 365 d&iacute;as</b> del a&ntilde;o que tanto usted, como sus socios y <b>clientes</b> podr&aacute;n tener a <b>documentos legales</b> y dem&aacute;s archivos que le sirven en su trabajo diario. La <b>privacidad</b> est&aacute; garantizada, y ser&aacute; usted quien le d&eacute; acceso a las personas que desee. Podr&aacute; alimentar <b>bases de datos</b> con confianza, sin riesgo a p&eacute;rdida de un archivo, ya que siempre se mantendr&aacute; guardada en la red. Adem&aacute;s, <b>Sistema de Gesti&oacute;n Legal</b> le enviar&aacute; <b>recordatorios de pago</b> a sus clientes, evit&aacute;ndole otro tedioso tr&aacute;mite.
		</p>
		<p class="p1_justify">
			El <b>Sistema de Gesti&oacute;n Legal</b> est&aacute; diseñado con novedosas herramientas de programaci&oacute;n que le permiten comunicarse con otros sistemas, como por ejemplo, su <b>p&aacute;gina web</b>. Con el <b>Sistema de Gesti&oacute;n Legal</b> sus <b>clientes</b> podr&aacute;n ingresar a una secci&oacute;n privada de la p&aacute;gina web de su <b>escritorio jur&iacute;dico</b> y consultar el <b>historial de sus casos</b> y enviarle mensajes, entre otras cosas. Dist&iacute;ngase de otros <b>escritorios jur&iacute;dicos</b> y demuestrele a sus clientes que usted est&aacute; en la <b>vanguardia tecnol&oacute;gica</b>. Si usted no tiene <b>p&aacute;gina web</b> tambi&eacute;n le ofrecemos la facilidad de cre&aacute;rsela y configurarla para que funcione junto con el <b>Sistema de Gesti&oacute;n Legal</b>.
		</p>
		<p class="p1_justify">
			Le invitamos a seguir explorando nuestra p&aacute;gina web <a href="http://www.sistemadegestionlegal.com" target="_blank">www.sistemadegestionlegal.com</a> para aprender m&aacute;s sobre el <b>Sistema de Gesti&oacute;n Legal</b>. Tambi&eacute;n le invitamos a probar el <a href="http://www.sistemadegestionlegal.com/demo" target="_blank">demo</a> del sistema a trav&eacute;s de <a href="http://www.sistemadegestionlegal.com/demo" target="_blank">www.sistemadegestionlegal.com/demo</a>
        </p>
			</div>
        </div>
      </div>
	  