
    <div id="main2">
      <!-- content2 -->
      <div id="content2" style="padding-bottom:10px;margin-bottom:10px">
        <div class="wrapper">
          <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/2page-title1.gif" alt="El equipo de desarrollo del SGL" /></div>
            	<div class="text_big_title" style="line-height:1em">El equipo de desarrollo del SGL</div>
            </div>              
                <p class="p1">La plataforma del <b>Sistema de Gesti&oacute;n Legal</b> es mantenida y actualizada 
                	por profesionales de la Computaci&oacute;n con m&aacute;s de 10 a&ntilde;os de experiencia en desarrollo 
                	de sistemas para la Web.  Nuestra vasta experiencia nos posiciona en un lugar privilegiado para el desarrollo
                	de aplicaciones que cumplan con los <a href="/sistema">objetivos propuestos</a>.</p>
                <p class="p1">Nuestro equipo de desarrollo es asesorado por <a href="/aliados">profesionales del &aacute;rea <b>legal</b></a>, quienes 
                con su experiencia laboral aportan valiosas ideas que se materializan dentro de nuestra plataforma, para su
                beneficio y el de su <b>Escritorio Jur&iacute;dico</b>. 
          </div>
          <div class="col-2">
            <div class="title1">
            	<div class="ico"><img src="/images/2page-title3.gif" alt="Nuestros Clientes" /></div>
            	<div class="text_big_title" style="line-height:1em">Nuestros Clientes</div>
            </div>              
            <cite style="margin-bottom:10px">&ldquo;El <b>Sistema de Gesti&oacute;n Legal</b> nos ha ayudado a automatizar las operaciones del
            d&iacute;a a d&iacute;a de nuestro <b>Escritorio Jur&iacute;dico</b>, y a posicionarnos dentro de la vanguardia tecnol&oacute;gica ..&rdquo;</cite>
            <h3>Daniel Tamayo, <a href="http://www.tamayo-tamayo.com" target="_blank">Escritorio Jur&iacute;dico Tamayo-Tamayo</a></h3>
          </div>
        </div>
      </div>
        <div id="content1" style="padding-top:10px;margin-top:-40px">
          <div class="indent">
            <div class="wrapper">
              <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/2page-title4.gif" alt="El equipo de desarrollo del SGL" /></div>
            	<div class="text_big_title" style="padding-top:10px;padding-left:10px">Estad&iacute;sticas</div>
            </div>              
                <p class="p1">Estad&iacute;sticas de uso. </p>
              </div>
              <div class="col-2">
            <div class="title1">
            	<div class="ico"><img src="/images/2page-title2.gif" alt="Otros Proyectos" /></div>
            	<div class="text_big_title" style="padding-top:10px;padding-left:70px">Otros Proyectos</div>
            </div>
            	<p class="p1">Estos son algunos otros proyectos en los que nuestro personal ha participado.</p>
                <ul class="list1">
                  <li><a href="http://www.estoesweb.com" target="_blank">www.estoesweb.com</a></li>
                  <li><a href="http://www.venezuelatuya.com" target="_blank">www.venezuelatuya.com</a></li>
                  <li><a href="http://www.zonaescolar.net" target="_blank">www.zonaescolar.net</a></li>
                </ul>
              </div>
              <div class="col-3">              
            <div class="title1" style="margin-bottom:-15px">
            	<div class="ico"><img src="/images/2page-title5.gif" alt="Otros Proyectos" /></div>            
            	<div class="text_big_title" style="padding-top:10px;padding-left:70px;margin-bottom:50px">&iexcl;Participa!</b></div>
            </div>
            	<p class="p1">Nuestro equipo est&aacute; siempre abierto a escuchar sugerencias para futuros desarrollos. Haz <a href="/contacto">clic</a> para ponerte en
            	contacto con nostros.</p>
            
                <div class="wrapper"><a href="/contacto" class="link1"><em><b>Enviar sugerencia</b></em></a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
