        <div id="content2">
          <div class="indent">
                <div class="title1">
                	<div class="ico"><img src="/images/7page-title.gif" alt="" /></div>
                	<div class="text_big_title">El Sistema de Gesti&oacute;n Legal</div>
                </div>
			<p class="p1" style="margin-top:50px;text-indent:25px">
El Sistema de Gesti&oacute;n Legal (<a href="/">www.sistemadegestionlegal.com</a>) es una marca privada y el uso indebido de la informaci&oacute;n contenida en este sitio acarrear&aacute; las sanciones civiles y penales a que haya lugar. Si desea comunicarse con nosotros por favor hagalo a la direcci&oacute;n de correo a continuaci&oacute;n:		
			</p>
            <p><img src="/images/emailcontacto.png"/></p>
          </div>
        </div>