        <div id="content1">
          <div class="indent">
            <div class="wrapper">
              <div class="col-3" style="width:900px">
                <div class="title1">
                	<div class="ico"><img src="/images/3page-title3.gif" alt="" /></div>
                	<div class="text_big_title">El Sistema de Gesti&oacute;n Legal</div>
                </div>
				<div class="text_title">Dirigido a <b>Escritorios Jur&iacute;dicos</b> y/o <b>profesionales de las leyes</b></div>
                <p class="p1_justify">
                Nuestro sistema va dirigido a <b>Escritorios Jur&iacute;dicos</b> y/o <b>profesionales de las leyes</b> que deseen automatizar y organizar toda la informaci&oacute;n 
                relacionada con el d&iacute;a a d&iacute;a de su actividad profesional, a la vez que deseen diferenciarse de la competencia y agregar valor a las relaciones con sus clientes.
                El <b>Sistema de Gesti&oacute;n Legal</b> tambi&eacute;n va dirigido a organizaciones sin fines de lucro u organismos gubernamentales que desempe&ntilde;en labores en el &aacute;rea
                jur&iacute;dica o de las leyes.</p>
				<div class="text_title">&iquest;C&oacute;mo funciona?</div>
                <p class="p1_justify">
	                El <b>Sistema de Gesti&oacute;n Legal</b> funciona bajo un novedoso paradigma bautizado como <b>"Cloud Computing"</b> o <b>"Computaci&oacute;n en la nube"</b>. En pocas palabras,
	                este nuevo esquema rompe con la manera tradicional de distribuir software (a trav&eacute;s de un CD u otro medio f&iacute;sico) y busca proveer software y servicios a trav&eacute;s de la Nube,
	                que no es mas que una met&aacute;fora para referirse a <b>Internet</b>. Posiblemente la manera m&aacute;s f&aacute;cil de relacionar este esquema con algo que seguramente ya conoce, es pensar en su 
	                proveedor de correo electr&oacute;nico como <b>Gmail</b>&copy; o <b>Hotmail</b>&copy;. El servicio de correo electr&oacute;nico es uno de tantos servicios que se ofrecen en <b>La Nube</b>.
                </p>
                <p class="p1_justify">El <b>Sistema de Gesti&oacute;n Legal</b> es un servicio que se ofrece a trav&eacute;s de <b>La Nube</b>, es decir, no tendr&aacute; que 
                recibir un CD o seguir (tediosas) instrucciones de instalaci&oacute;n. Lo &uacute;nico que usted debe tener es un navegador Web y una conexi&oacute;n a <b>Internet</b>.
                Es por esto que el <b>Sistema de Gesti&oacute;n Legal</b> es una plataforma viva que se actualizar&aacute; constantemente sin necesidad de que usted haga nada. Usted no est&aacute;
                adquiriendo un producto que se volver&aacute; obsoleto en el futuro, sino que est&aacute;ra participando de una plataforma en constante crecimiento.
                <p class="p1_justify">A continuaci&oacute;n le presentamos una representaci&oacute;n esquem&aacute;tica de <b>La Nube</b>:
                </p>
                <p class="p1_imagen"><img src="/images/lanube.jpg"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://www.tecnocodigo.com' target="_blank">http://www.tecnocodigo.com</a></p>
				<div class="text_title">Ventajas del Sistema de Gesti&oacute;n Legal</div>
				<p  class="p1_justify">
					Las ventajas de este nuevo esquema son muchas, mas algunas de las principales son:
					<ul class="list2">
						<li>Recordatorio autom&aacute;tico de lapsos procesales. No olvide nunca m&aacute;s una fecha importante.</li>
						<li>Usted mismo podr&aacute; otorgale acceso al sistema a su personal de confianza, sin depender de terceros.</li>
						<li>Base de datos en l&iacute;nea, con respaldos autom&aacute;ticos. No debe preocuparse m&aacute;s por perder alg&uacute;n documento ya que siempre lo tendr&aacute; en l&iacute;nea.</li>
						<li>B&uacute;squeda f&aacute;cil de cualquier informaci&oacute;n registrada en el sistema.</li>
						<li>Env&iacute;o de notificaciones autom&aacute;ticas de recordatorio de pago a sus clientes. Evite llamadas telef&oacute;nicas innecesarias.</li>
						<li>Acceso a la historia de cada uno de sus casos, con posibilidad de descarga de cualquier documento relevante.</li>
						<li>Acceso al sistema desde dispositivos m&oacute;biles, &uacute;til cuando se encuentre en tribunales y necesite acceder a su informaci&oacute;n.</li>
						<li>Capte clientes a trav&eacute;s de Internet.</li>
						<li>Construya una base de datos de clientes y prospectos.</li>
						<li>Sus clientes tendr&aacute;n acceso a la &uacute;ltima informaci&oacute;n y a la historia de sus casos, a trav&eacute;s del portal Web de su <b>Escritorio Jur&iacute;dico</b>, &uacute;nicamente a sus casos (si usted lo desea).</li>
						<li>Si ya posee una p&aacute;gina web int&eacute;grela con el Sistema de Gesti&oacute;n Legal. Si no posee p&aacute;gina, nosotros se la desarrollamos.</li>
						<li>Construya una base de datos de leyes y posici&oacute;nese en buscadores tales como <b>Google</b>&copy;.</li>
						<li>Servicio configurable seg&uacute;n sus necesidades.</li>
						<li>Servicio disponible 24/7/365 tanto para usted como para sus clientes.</li>
						<li>Estas son s&oacute;lo algunas de las ventajas del <b>Sistema de Gesti&oacute;n Legal</b>...</li>
					</ul>
				</p>
				<p class="p1_justify" style="font-size:larger;padding:2em">Le invitamos a probar el <a href="/demo">demo</a> del <b>Sistema de Gesti&oacute;n Legal</b> 
				y corroborar por usted mismo las ventajas de trasladar su <b>Escritorio Jur&iacute;dico a la Web</b>. Si usted ya prob&oacute; el demo y est&aacute; interesado
				en obtener m&aacute;s informaci&oacute;n, no dude en <a href="/contacto">contactarnos</a>
                </p>
                <div class="wrapper" style="margin-bottom:30px"><a href="/demo" class="link1"><em><b>Ver DEMO</b></em></a><a style="margin-left:300px" href="/contacto" class="link1"><em><b>Cont&aacute;ctenos</b></em></a></div>
                <div class="title1">
                	<div class="ico"><img src="/images/2page-title4.gif" alt="" /></div>
                	<div class="text_big_title">Algunas Pantallas del Sistema de Gesti&oacute;n Legal</div>
                </div>
				<div class="text_title">El Login al Sistema</div>
                <p class="p1_imagen"><img src="/images/elsistema/login.png"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://admin.sistemadegestionlegal.com' target="_blank">http://admin.sistemadegestionlegal.com</a></p>
				<div class="text_title">Pantalla Principal</div>
                <p class="p1_imagen"><img src="/images/elsistema/portada.png"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://admin.sistemadegestionlegal.com' target="_blank">http://admin.sistemadegestionlegal.com</a></p>
				<div class="text_title">M&oacute;dulo de Casos</div>
                <p class="p1_imagen"><img src="/images/elsistema/casos.png"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://admin.sistemadegestionlegal.com' target="_blank">http://admin.sistemadegestionlegal.com</a></p>
				<div class="text_title">M&oacute;dulo de Clientes</div>
                <p class="p1_imagen"><img src="/images/elsistema/clientes.png"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://admin.sistemadegestionlegal.com' target="_blank">http://admin.sistemadegestionlegal.com</a></p>
				<div class="text_title">M&oacute;dulo de Abogados</div>
                <p class="p1_imagen"><img src="/images/elsistema/abogados.png"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://admin.sistemadegestionlegal.com' target="_blank">http://admin.sistemadegestionlegal.com</a></p>
				<div class="text_title">M&oacute;dulo de Leyes</div>
                <p class="p1_imagen"><img src="/images/elsistema/leyes.png"/></p>
				<p class="p1_foot_imagen">Fuente de la im&aacute;gen: <a href='http://admin.sistemadegestionlegal.com' target="_blank">http://admin.sistemadegestionlegal.com</a></p>
                <div class="wrapper" style="margin-bottom:30px"><a href="/demo" class="link1"><em><b>Ver DEMO</b></em></a><a style="margin-left:300px" href="/contacto" class="link1"><em><b>Cont&aacute;ctenos</b></em></a></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="main2">
      <!-- content2 -->
      <div id="content2">
        <div class="wrapper">
          <div class="col-1">
            <div class="title1">
            	<div class="ico"><img src="/images/1page-title1.gif" alt="El equipo de desarrollo del SGL" /></div>
            	<div class="text_big_title"n style="line-height:1em">El equipo de desarrollo del SGL</div>
            </div>
			<p class="p1" style="line-height:1.25em">Detr&aacute;s del escenario existe un equipo de profesionales que mantienen el <b>Sistema de Gesti&oacute;n Legal</b> en permanente desarrollo y actualizaci&oacute;n, con el fin
            de que usted disfrute de las &uacute;ltimas tecnolog&iacute;as en Internet. Le invitamos a conocer un poco m&aacute;s sobre nuestra empresa.</p>
            <div class="wrapper"><a href="/nosotros" class="link1"><em><b>Ver m&aacute;s sobre la empresa...</b></em></a></div>
          </div>
          <div class="col-2">
            <div class="title1">
            	<div class="ico"><img src="/images/3page-title5.gif" alt="Aliados de nuestra empresa" /></div>
            	<div class="text_big_title"n style="line-height:1em">Aliados de nuestra empresa</div>
            </div>
            
            <p class="p1">Conozca a algunos de nuestros aliados</p>
            <div class="wrapper">
              <div class="col-1">
                <ul class="list1">
                  <li><a href="/aliados">Clientes:</a></li>
                  <li><a href="http://www.tamayo-tamayo.com" target="_blank">Escritorio Jur&iacute;dico Tamayo-Tamayo</a></li>
                  <li>Escritorio Jur&iacute;dico Areyan Salazar & Asociados</li>
                </ul>
              </div>
              <div class="col-2">
                <ul class="list1">
                  <li><a href="/aliados">Proveedores:</a></li>
                  <li><a href="http://www.inmotionhosting.com" target="_blank">Inmotionhosting.com</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>