<h2 id="tituloConfiguracion">Opciones de Configuraci&oacute;n</h2>
<script type="text/javascript" src="/js/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>

		<script type="text/javascript">
			$(function(){

				// Accordion
				$("#accordion").accordion({ header: "h3" });
				
			});
		</script>



<div id="accordion" class="ui-accordion ui-widget ui-helper-reset ui-accordion-icons" role="tablist">
	<div class="">
		<h3 id="tituloEmail" class="ui-accordion-header ui-helper-reset ui-state-active ui-corner-top ui-state-hover" role="tab" aria-expanded="true" aria-selected="true" tabindex="0"><span class="ui-icon ui-icon-triangle-1-s"></span><a href="#" tabindex="-1">Emails Autom&aacute;ticos</a></h3>
		<div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom ui-accordion-content-active" style="height: 14px; display: block; overflow: auto; padding-top: 11px; padding-bottom: 11px;" role="tabpanel">
			<ul class="list-2">
				<li><a href="/configuracion/emails/remitente">Definir Remitente y Destinatario</a></li>
				<li><a href="/configuracion/emails/email/tipo/registro">Email de Registro</a></li>
				<li><a href="/configuracion/emails/email/tipo/pago">Email de Pago</a></li>
				<li><a href="/configuracion/emails/email/tipo/cambioestatus">Email de Cambio de Estatus de un Caso</a></li>
			</ul>
		</div>
	</div>
	<div class="">
		<h3 id="tituloCuenta" class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all" role="tab" aria-expanded="false" aria-selected="false" tabindex="-1"><span class="ui-icon ui-icon-triangle-1-e"></span><a href="/configuracion/cuentas" tabindex="-1">Cuentas Bancarias</a></h3>
		<div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" style="height: 14px; overflow: auto; display: none; padding-top: 11px; padding-bottom: 11px;" role="tabpanel">Haga clic <a href="/configuracion/cuentas">aqu&iacute;</a> para editar las cuentas bancarias</div>
	</div>
</div>